# Generated by Django 4.0.3 on 2022-04-02 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0002_alter_image_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Уникальный токен'),
        ),
        migrations.AlterField(
            model_name='image',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.album', verbose_name='Альбом'),
        ),
        migrations.AlterField(
            model_name='image',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
